feat: build comment item
implude/meat-in-android pull request #23
Opened 2021-09-15 12:37 UTC by Gijuno

2021-09-15 13:08 UTC, nutyworks requested changes

2021-09-15 13:08 UTC, nutyworks commented on app/src/main/java/app/meatin/ui/composables/CommentItem.kt
> +    date: String,
타입 LocalDateTime으로 해주세요

2021-09-15 13:08 UTC, nutyworks commented on app/src/main/java/app/meatin/ui/composables/CommentItem.kt
> +) {
There is no `modifier: Modifier` parameter.

2021-09-16 11:15 UTC, nutyworks requested changes
이전 conversation이 해결되지 않았습니다.

2021-09-18 02:00 UTC, nutyworks requested changes

2021-09-18 02:00 UTC, nutyworks commented on app/src/main/java/app/meatin/ui/composables/CommentItem.kt
> +        Row {
아래에 2dp 패딩이 있어야 합니다.

2021-09-18 02:17 UTC, nutyworks commented on app/src/main/java/app/meatin/ui/composables/CommentItem.kt
> +    Column {
`modifier`이 최상단 view에 적용되어야 합니다.

2021-09-18 03:29 UTC, Gijuno commented on app/src/main/java/app/meatin/ui/composables/CommentItem.kt
> +        Row {
헐.. 안보였네요

2021-09-18 03:35 UTC, Gijuno commented on app/src/main/java/app/meatin/ui/composables/CommentItem.kt
> +    Column {
![image](https://user-images.githubusercontent.com/46197097/133871286-f34a6bf2-bad0-4da1-9f16-80a9faa508d8.png)
적용시킨다는 뜻이 이게 맞나요..?

2021-09-18 03:57 UTC, nutyworks commented on app/src/main/java/app/meatin/ui/composables/CommentItem.kt
> +    Column {
```kt
Column(modifier) {
    // ...
}
```

2021-09-19 04:10 UTC, nutyworks approved these changes

2021-09-23 12:20 UTC, jhk2004 approved these changes

2021-09-23 12:22 UTC, merged