feat: ingredient-item
implude/meat-in-android pull request #31
Opened 2021-09-16 12:42 UTC by namjungwook8133

2021-09-18 01:55 UTC, nutyworks requested changes

2021-09-18 01:55 UTC, nutyworks commented on app/src/main/java/app/meatin/ui/composables/IngredientItem.kt
> +    content: String,
매개변수 이름과 타입이 적절하지 않아 보입니다.
* `ingredientItem` > `name`
* `ingredientNumber: String` > `quantity: Number`
  * `ingredientNumber` 매개변수가 숫자만 받으므로 단위에 대한 매개변수도 추가해야 합니다.
* `essential: String` > `isEssential: Boolean`
* `content` > `description`

2021-09-18 01:55 UTC, nutyworks commented on app/src/main/java/app/meatin/ui/composables/IngredientItem.kt
> +
불필요한 빈 줄이 삽입되었습니다.

2021-09-18 01:55 UTC, nutyworks commented on app/src/main/java/app/meatin/ui/composables/IngredientItem.kt
> +            .border(1.dp, Color.Gray),
![image](https://user-images.githubusercontent.com/48619865/133868288-1a8e81c4-82e4-4cbd-a353-207352c8be01.png)
보더가 잘려 있습니다.

2021-09-18 01:55 UTC, nutyworks commented on app/src/main/java/app/meatin/ui/composables/IngredientItem.kt
> +                    Spacer(modifier = Modifier.width(55.dp))
![image](https://user-images.githubusercontent.com/48619865/133868385-598af0ce-57e4-46a6-bc80-2d266c74e4cf.png)
`ingredientItem`과 `ingredientNumber`가 더 긴 값으로 변경되었을 때 문제가 발생했습니다. 패딩을 조절하거나 "필수"를 오른쪽 정렬해야 합니다.

2021-10-06 11:58 UTC, namjungwook8133 commented
ㅠㅠ

2021-10-06 12:08 UTC, nutyworks requested changes
Due to d9422a35c9a8d67031fe17f916ca0cda3863ec2d, all `Text` composables should be replaced with `CoreText`.

2021-10-08 03:34 UTC, nutyworks requested changes

2021-10-08 03:34 UTC, nutyworks commented on app/src/main/java/app/meatin/ui/composables/IngredientItem.kt
>                  .width(134.dp)
You should remove this line.

2021-10-08 11:24 UTC, nutyworks approved these changes
LGTM

2021-10-09 22:38 UTC, jhk2004 approved these changes

2021-10-10 03:09 UTC, merged