fix(presentation): ellipt profile button text
implude/meat-in-android pull request #54
Opened 2021-10-07 13:21 UTC by jhk2004

사용자 이름의 길이가 View를 넘어가는 오류를 수정했습니다

2021-10-08 03:38 UTC, nutyworks approved these changes

2021-10-08 08:16 UTC, Gijuno requested changes
![image](https://user-images.githubusercontent.com/46197097/136522175-27983e34-7249-4880-8dc6-1ea0432e7424.png)
구현 여부 확인 부탁드립니다

2021-10-08 11:03 UTC, nutyworks commented
> ![image](https://user-images.githubusercontent.com/46197097/136522175-27983e34-7249-4880-8dc6-1ea0432e7424.png) 구현 여부 확인 부탁드립니다

![image](https://user-images.githubusercontent.com/48619865/136545735-c3f6bbc0-c149-432f-ba08-26796d1d9fe1.png)
잘 됩니다. 그럴 때는 request changes 말고 그냥 comment 해주세요.

2021-10-09 15:06 UTC, Gijuno approved these changes

2021-10-09 15:21 UTC, merged