feat(presentation): add `BadgedUser` component
implude/meat-in-android pull request #64
Opened 2021-10-13 12:40 UTC by nutyworks

Closes #61.

2021-10-13 13:11 UTC, Gijuno requested changes
badge와 classes 사이에 4dp 패딩이 필요합니다.

2021-10-13 13:13 UTC, Gijuno submitted a review, later dismissed

2021-10-13 13:16 UTC, jhk2004 approved these changes, later dismissed

2021-10-20 11:07 UTC, Gijuno approved these changes

2021-10-20 11:24 UTC, jhk2004 requested changes
![image](https://user-images.githubusercontent.com/64252172/138083972-4dc0a7ae-b3e9-464a-93b7-8ea3a55060b2.png)

2021-10-20 11:36 UTC, jhk2004 approved these changes

2021-10-20 11:36 UTC, merged