feat(presentation): build post detail screen
implude/meat-in-android pull request #66
Opened 2021-10-14 13:35 UTC by Gijuno

2021-10-21 12:11 UTC, jhk2004 requested changes

2021-10-21 12:11 UTC, jhk2004 commented on app/src/main/java/app/meatin/ui/composables/PostDetailScreen.kt
> +//            }
이게 몰까니~

2021-10-28 11:18 UTC, jhk2004 requested changes
![image](https://user-images.githubusercontent.com/64252172/139244887-b287f018-2f31-4ef8-988e-9725c422ac2a.png)
![image](https://user-images.githubusercontent.com/64252172/139244910-856381ff-9fba-423b-9571-9af67728f506.png)
날짜 형식 수정해주세요
그림자 약하게 바꿔주세요
(뱃지 상태가 이상해요)

연결된 레시피 클릭 먹여주세요(전체로)

댓글 입력 안돼요

댓글 클릭 가능해야 돼요 

![image](https://user-images.githubusercontent.com/64252172/139245611-c186ea99-3c36-43b6-af3f-54c060eeadf8.png)
스크롤이 끝까지 안 내려가요

2021-11-10 13:31 UTC, jhk2004 submitted a review, later dismissed

2021-11-11 11:35 UTC, namjungwook8133 approved these changes, later dismissed

2021-11-13 11:15 UTC, nutyworks requested changes

2021-11-13 11:15 UTC, nutyworks commented on app/src/main/java/app/meatin/ui/composables/PostDetailScreen.kt
> +                    )
![image](https://user-images.githubusercontent.com/48619865/141632748-f13e5118-f13e-4574-a47c-dfd3f746eb69.png)

* end constraint 없음

2021-12-01 09:18 UTC, Gijuno commented on app/src/main/java/app/meatin/ui/composables/PostDetailScreen.kt
> +                    )
fixed at a9968bf

2021-12-14 11:32 UTC, nutyworks approved these changes

2021-12-15 05:51 UTC, jhk2004 approved these changes

2021-12-15 06:08 UTC, merged