feat(presentation): add `LoginScreen` composable
implude/meat-in-android pull request #81
Opened 2021-11-25 12:40 UTC by nutyworks

Resolves #80.

`enum class LoginState` has two states; NICKNAME, PASSWORD.
`onNickNameConfirm` callback is called when the user presses confirm button (or keyboard IME button) in the NICKNAME state.
`onBackPressedInPassword` callback is called when the user presses the back button in the PASSWORD state; you may want to go back to the NICKNAME state.
`onPasswordConfirm` callback is called when the user presses confirm button (or keyboard IME button) in the PASSWORD state.

2021-12-01 06:15 UTC, Gijuno commented
패스워드 필드 작성 상태에서 닉네임 필드 작성/수정 불가능한 부분이 UX적으로 조금 좋지 않을 듯 합니다.
이 부분이 의도되었고 강력하게 원하시는 부분이라면 닉네임 필드가 회색처리 되는 등 시각적 요소도 추가하면 좋을것 같아요.

2021-12-01 06:17 UTC, Gijuno commented
닉네임은 최소2글자, 비밀번호는 최소8글자 형식으로 갖춰져 있는데,
닉네임이 1글자여도 확인 버튼만 비활성화될 뿐, 사용자에게 따로 노티가 없어서 주의깊게 보지 않았다면 회원가입에 어려움을 느낄 수 있어요.

닉네임이 1글자 이하라면 패스워드 입력창으로 못 넘어가게 한다던가, 혹은 다른 노티가 있었으면 좋겠습니다.
(시간 관계상 패스 가능)

2021-12-01 07:04 UTC, Gijuno commented
- 입력값 검증에 대한 시각적 요소(색의 변화, 텍스트 표현)를 추가하는게 좋겠습니다
- 입력/검증이 완료된 필드도 클릭하면 편집할 수 있도록 활성화가 되어야 하고
- 키보드가 나타났을 때 아래 액션 버튼이 클릭 가능하도록 위로 올라와야합니다

...만 시간이 없으니 그냥 넘어가도... 무방하지 않을까.. 싶은데...

2021-12-01 07:16 UTC, jhk2004 submitted a review, later dismissed

2021-12-01 07:17 UTC, Gijuno requested changes
상기한 사항들 추가 커맨트 후 수정 부탁드립니다

2021-12-13 08:39 UTC, nutyworks commented
> * 입력값 검증에 대한 시각적 요소(색의 변화, 텍스트 표현)를 추가하는게 좋겠습니다
> 
>     * 입력/검증이 완료된 필드도 클릭하면 편집할 수 있도록 활성화가 되어야 하고
> 
>     * 키보드가 나타났을 때 아래 액션 버튼이 클릭 가능하도록 위로 올라와야합니다
> 
> 
> ...만 시간이 없으니 그냥 넘어가도... 무방하지 않을까.. 싶은데...
> 
> _by 정한_

* 키보드가 나타났을 때 아래 액션 버튼이 클릭 가능하도록 위로 올라와야합니다
해당 이슈는 아래 코드를 Activity에 추가하면 해결됩니다.
```kt
window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
```

2021-12-13 09:29 UTC, Gijuno approved these changes
오 몰랐네요 감사합니다

2021-12-14 11:28 UTC, jhk2004 approved these changes

2021-12-14 11:34 UTC, merged