feat(presentation): build barocook fin
implude/meat-in-android pull request #89
Opened 2021-12-15 13:05 UTC by jhk2004

![image](https://user-images.githubusercontent.com/64252172/146191658-68e70e53-8b3c-474d-b7bc-4da6e910b846.png)

2021-12-15 13:46 UTC, nutyworks approved these changes, later dismissed

2021-12-15 13:58 UTC, Gijuno requested changes
`상황, situation` 보다는 `환경, env` 로 바꿔주세요~

2021-12-16 02:07 UTC, Gijuno approved these changes

2021-12-16 05:30 UTC, nutyworks approved these changes

2021-12-16 05:30 UTC, merged